// Code generated by hertz generator.

package main

import (
	"github.com/clg-CloudWeGo/gateway/biz/handler/hertzSvr/gateway"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.POST("/gateway/:service/:method", gateway.Gateway)

	// your code ...
}
