// Code generated by hertz generator.

package idlManager

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	idlManager "github.com/clg-CloudWeGo/gateway/biz/model/hertzSvr/idlManager"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

var idlQueryUrl = "http://localhost:8889/idl/query"

type IDLInfo struct {
	Name string `json:"name"`
	Idl  string `json:"idl"`
}

// UpdateIDL .
// @router /idl/update [POST]
func UpdateIDL(ctx context.Context, c *app.RequestContext) {
	var err error
	var req idlManager.IDLMessage
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(idlManager.IDLResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetIDLContent get the idl content according to service name
func GetIDLContent(svcName string) string {
	fmt.Println("in GetIDLContent")
	request, err := http.NewRequest("GET", idlQueryUrl+"?name="+svcName, nil)
	request.Header.Set("Content-Type", "application/json")
	if err != nil {
		panic("Error: failed to query IDL---" + err.Error())
	}
	client := &http.Client{}
	response, err := client.Do(request)
	defer response.Body.Close()
	body, err := io.ReadAll(response.Body)
	if err != nil {
		panic("Error: failed to read body---" + err.Error())
	}
	var resp IDLInfo
	err = json.Unmarshal(body, &resp)
	fmt.Println(resp)
	if err != nil {
		panic("Error: failed to transform byte body into json---" + err.Error())
	}
	return resp.Idl
}
