// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	Gateway "Gateway/biz/router/Gateway"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	Gateway.Register(r)
}
