// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	hertzSvr_service "github.com/clg-CloudWeGo/idlmanagementservice/biz/router/hertzSvr/service"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	hertzSvr_service.Register(r)
}
